name: Continuous Integration

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ansi

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --diff --dry-run --allow-risky=yes

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run PHPUnit (opcjonalnie, jeśli masz testy)
        run: vendor/bin/phpunit
